project_name: kabuka
before:
  hooks:
    - go mod tidy
release:
  github:
    owner: shionit
    name: kabuka
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kabuka
    binary: kabuka
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: 'checksums.txt'
