project_name: kabuka
release:
  github:
    owner: shionit
    name: kabuka
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  main: ./cmd/kabuka
  binary: kabuka
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
