name: Lint Dockerfile

on:
  push:
    paths:
      - ".devcontainer/Dockerfile"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ".devcontainer/Dockerfile"
